version: '3.7'

services:
  api:
    build: ./company-api
    network_mode: bridge
    restart: on-failure
    links:
      - sql
    ports:
      - '8080:8080'
    depends_on:
      - sql
    environment:
      SQL_PORT: 1433
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    network_mode: bridge
    ports:
        - '1433:1433'
    environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'Secret!Secret'
    volumes:
      - sql_data:/var/lib/sql

volumes:
    sql_data: