version: '3.7'

services:
  api:
    build: ./company-api
    network_mode: bridge
    restart: on-failure
    links:
      - postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SQL_PORT: 5432
  postgres:
    network_mode: bridge
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./postgres-data:/var/lib/postgresql

volumes:
  postgres-data: