version: '3.7'

services:
  api:
    build: ./company-api
    network_mode: bridge
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      DATABASE_DATABASE: ${DATABASE}
      DATABASE_IP: ${HOST}
      DATABASE_USER: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
