version: '3'

services:
  api:
    build: ./company-api
    restart: on-failure
    links:
      - sql
    ports:
      - "8080:8080"
    depends_on:
      - sql
    environment:
      PORT: 1433
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Secret!Secret"
    volumes:
      - sql_data:/var/lib/sql

networks:
  default:
    external:
      name: bridge

volumes:
    sql_data: