version: '3.7'

services:
  web:
    build: ./
    network_mode: bridge
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_DATABASE: ${DATABASE}
      DATABASE_IP: ${HOST}
      DATABASE_USER: ${USER}
      DATABASE_PASSWORD: ${PASSWORD}
      PORT: ${PORT}
